// Curated discussion topics organized by category.
// Each prebuilt topic gets a stable id so it can be favourited / referenced.

export type CategoryId =
  | "philosophy"
  | "technology"
  | "hypothetical"
  | "relationships"
  | "career"
  | "creative"
  | "ethics"
  | "culture"
  | "event";

export interface CategoryMeta {
  id: CategoryId;
  label: string;
  description: string;
  /** Tailwind text color class for accents/badges */
  text: string;
  /** Tailwind bg tint class (soft) */
  bg: string;
  /** Tailwind border class */
  border: string;
  /** A solid dot color */
  dot: string;
  /** Lucide icon name (resolved on the client) */
  icon: string;
}

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "philosophy",
    label: "Philosophy",
    description: "Deep questions about life, mind & meaning",
    text: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-500/10",
    border: "border-violet-500/30",
    dot: "bg-violet-500",
    icon: "Brain",
  },
  {
    id: "technology",
    label: "Technology",
    description: "The future, gadgets & digital life",
    text: "text-teal-600 dark:text-teal-400",
    bg: "bg-teal-500/10",
    border: "border-teal-500/30",
    dot: "bg-teal-500",
    icon: "Cpu",
  },
  {
    id: "hypothetical",
    label: "Hypothetical",
    description: "What-if scenarios & wild imagination",
    text: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    dot: "bg-amber-500",
    icon: "Rocket",
  },
  {
    id: "relationships",
    label: "Relationships",
    description: "People, connection & social dynamics",
    text: "text-rose-600 dark:text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30",
    dot: "bg-rose-500",
    icon: "Users",
  },
  {
    id: "career",
    label: "Career",
    description: "Work, ambition & professional growth",
    text: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    dot: "bg-emerald-500",
    icon: "Briefcase",
  },
  {
    id: "creative",
    label: "Creative",
    description: "Imagination, art & storytelling",
    text: "text-fuchsia-600 dark:text-fuchsia-400",
    bg: "bg-fuchsia-500/10",
    border: "border-fuchsia-500/30",
    dot: "bg-fuchsia-500",
    icon: "Palette",
  },
  {
    id: "ethics",
    label: "Ethics & Debate",
    description: "Tricky dilemmas worth arguing about",
    text: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/30",
    dot: "bg-orange-500",
    icon: "Scale",
  },
  {
    id: "culture",
    label: "Travel & Culture",
    description: "Places, traditions & ways of living",
    text: "text-pink-600 dark:text-pink-400",
    bg: "bg-pink-500/10",
    border: "border-pink-500/30",
    dot: "bg-pink-500",
    icon: "Globe",
  },
  {
    id: "event",
    label: "Event",
    description: "Sheep or Detective? Check First Before You Join the Fight",
    text: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    dot: "bg-blue-500",
    icon: "ShieldAlert",
  },
];

export const CATEGORY_MAP: Record<CategoryId, CategoryMeta> = CATEGORIES.reduce(
  (acc, c) => {
    acc[c.id] = c;
    return acc;
  },
  {} as Record<CategoryId, CategoryMeta>,
);

export function getCategoryMeta(id: string): CategoryMeta {
  return (
    CATEGORY_MAP[id as CategoryId] ?? {
      id: "creative" as CategoryId,
      label: id.charAt(0).toUpperCase() + id.slice(1),
      description: "",
      text: "text-fuchsia-600 dark:text-fuchsia-400",
      bg: "bg-fuchsia-500/10",
      border: "border-fuchsia-500/30",
      dot: "bg-fuchsia-500",
      icon: "Sparkles",
    }
  );
}

export interface Topic {
  id: string;
  text: string;
  category: CategoryId;
  source: "prebuilt" | "custom";
  spiciness?: number;
  tags?: string[];
}

// The curated, prebuilt topic bank.
const RAW_TOPICS: Record<CategoryId, string[]> = {
  philosophy: [
    "If you could know the absolute truth to one question, what would you ask?",
    "Is it better to be a satisfied pig or a dissatisfied Socrates?",
    "Does free will truly exist, or is it an illusion created by our brain?",
    "What gives a human life meaning — achievement, connection, or something else?",
    "If a tree falls in a forest and no one hears it, does it make a sound?",
    "Can morality exist without religion or a higher power?",
    "Is identity something you're born with or something you create?",
    "Would you rather know how the universe ends or how it began?",
    "Are we the same person we were ten years ago?",
    "Is suffering necessary to appreciate happiness?",
    "Can a society be truly just, or is justice always partial?",
    "Does language shape thought, or does thought shape language?",
    "Is happiness a choice or a consequence of circumstance?",
    "Can true altruism exist, or is every act ultimately self-serving?",
    "If you could erase one memory, would you? Which one?",
    "Is it better to be a small part of something great or the center of something small?",
    "Does the universe have a purpose, or is it indifferent?",
    "Are emotions rational, or do they exist outside of reason?",
    "What separates humans from other animals — if anything?",
    "Is there a difference between living and merely existing?",
    "If everyone forgot you existed tomorrow, would your life have mattered?",
    "Can you ever truly know another person's experience?",
    "Is boredom a modern luxury or a fundamental human condition?",
    "Would a perfectly predictable life be worth living?",
    "Is the self an illusion, a story we tell ourselves?",
    "Can something be objectively beautiful, or is beauty always subjective?",
    "Is it worse to never try and fail, or to fail after trying hard?",
    "Does the passage of time exist, or is it a feature of human consciousness?",
    "Are we obligated to future generations we'll never meet?",
    "What would you be willing to die for — and how do you know you're right?",
  ],
  technology: [
    "Will AI eventually make most current jobs obsolete?",
    "Should there be a universal right to disconnect from the internet?",
    "Is social media a net positive or net negative for humanity?",
    "Would you upload your consciousness to a computer if you could?",
    "Should children under 16 be banned from smartphones?",
    "Is technological progress always a good thing?",
    "Could humanity survive a complete collapse of the digital infrastructure?",
    "Should algorithms that shape public opinion be regulated?",
    "Is privacy a fundamental human right in the digital age?",
    "Will cryptocurrency replace traditional money in your lifetime?",
    "Do smart homes make us safer or more vulnerable?",
    "Is the metaverse the future of human interaction?",
    "Should self-driving cars be programmed to prioritize the driver or pedestrians?",
    "Is technology making us more connected or more isolated?",
    "Should there be a 'death switch' for your digital accounts?",
    "Can a machine ever truly be creative, or only imitate creativity?",
    "Is the convenience of streaming worth the death of physical media?",
    "Should tech companies be broken up when they get too big?",
    "Will virtual reality ever feel as real as physical reality?",
    "Are we too dependent on GPS and navigation apps?",
    "Should there be an age limit for social media influencers?",
    "Is the 'always-on' work culture a product of technology or choice?",
    "Could you live for a month completely offline — would you want to?",
    "Should AI-generated content be labeled by law?",
    "Is targeted advertising a fair trade for free services?",
    "Will humans ever colonize Mars in your lifetime — and should we?",
    "Is the decline of handwriting a loss worth mourning?",
    "Should deepfakes be banned outright, or regulated?",
    "Do we own our digital purchases, or just rent them?",
    "What technology do you wish had never been invented?",
  ],
  hypothetical: [
    "If you could have dinner with any historical figure, who would it be?",
    "What would you do if you could pause time for everyone but yourself?",
    "If you had to relive one day of your life forever, which would it be?",
    "Would you take a pill that guaranteed success but removed all surprise?",
    "If animals could talk for one day, what would change?",
    "You can master any skill instantly — which do you choose?",
    "If you could teleport anywhere right now, where would you go?",
    "Would you rather know the future or change the past?",
    "If you could only keep five possessions, what would they be?",
    "What would society look like if no one needed sleep?",
    "If you could be fluent in every language, would you travel more?",
    "Would you accept immortality if everyone you loved stayed mortal?",
    "If you could swap lives with anyone for a week, who would it be?",
    "What would you do with a million dollars that had to be spent in 24 hours?",
    "If you could bring back one extinct species, which would it be?",
    "You can only eat one cuisine for the rest of your life — what is it?",
    "If you could restart your life but keep your memories, would you?",
    "What would Earth be like if humans had never existed?",
    "If you could witness any event in history, which would you choose?",
    "Would you rather be able to fly or become invisible?",
    "If every person suddenly had one superpower, what would society look like?",
    "You can erase one invention from history — what is it?",
    "If you could live in any fictional world, which would you pick?",
    "What would you do if you were the last person on Earth?",
    "If you could read minds, would you want to?",
    "Would you rather always be 10 minutes late or 20 minutes early?",
    "If you had to teach one subject for the rest of your life, what would it be?",
    "You can instantly learn the answer to one mystery — which?",
    "If money were no object, what would you spend your life doing?",
    "What rule would you impose on the whole world if you could?",
  ],
  relationships: [
    "What makes a friendship last a lifetime?",
    "Is honesty always the best policy in a relationship?",
    "Can you truly be friends with an ex-partner?",
    "What's the most important quality in a life partner?",
    "How do you know when to walk away from a toxic relationship?",
    "Is it possible to love two people equally at the same time?",
    "What's the difference between love and attachment?",
    "Should couples share all their finances or keep them separate?",
    "How do you rebuild trust once it's been broken?",
    "Is jealousy ever a healthy emotion?",
    "What role should family play in your major life decisions?",
    "Can long-distance relationships really work long-term?",
    "Is it possible to stay friends with someone you've outgrown?",
    "How do you apologize well, and why is it so hard?",
    "What's the line between supporting and enabling someone?",
    "Can opposites really make a relationship work long-term?",
    "How much should you sacrifice for the people you love?",
    "Is it healthy to keep secrets from those closest to you?",
    "What makes someone a 'good listener'?",
    "Should you ever stay in a relationship just for the children?",
    "How do you handle a friend who's always negative?",
    "Is forgiveness always the right thing to do?",
    "What's the best way to repair a friendship after a fight?",
    "Can you love someone and not like them at the same time?",
    "How important is shared interests vs. shared values in a relationship?",
    "Is it ever too late to reconnect with someone from your past?",
    "What's the hardest part about making friends as an adult?",
    "Should you tell a friend an uncomfortable truth if it might hurt them?",
    "How do you set boundaries with family without feeling guilty?",
    "What does a healthy disagreement look like?",
  ],
  career: [
    "Is it better to be a specialist or a generalist today?",
    "Would you rather have a job you love that pays little, or one you hate that pays well?",
    "At what point does ambition become unhealthy?",
    "Should everyone experience unemployment at least once?",
    "Is a four-day work week realistic for most industries?",
    "What matters more in hiring — experience or potential?",
    "How do you balance career growth with personal life?",
    "Is failure an essential part of professional success?",
    "Should leaders be chosen for charisma or competence?",
    "When is it time to leave a stable job for an uncertain one?",
    "Does the traditional resume still matter in 2025?",
    "What's the single most underrated career skill?",
    "Is networking more about who you know or what you know?",
    "Should salary be transparent across a whole company?",
    "How important is passion versus stability in choosing a career?",
    "Is burnout a personal failure or a structural problem?",
    "Should internships always be paid?",
    "What's the value of a college degree in 2025 compared to experience?",
    "Can you build a meaningful career without ever managing anyone?",
    "Is the side hustle culture helping or harming us?",
    "How do you know if you're truly good at your job?",
    "Should retirement still be a goal, or is it outdated?",
    "What's the biggest myth about success?",
    "Is it ethical to stay in an industry you think harms the world?",
    "How do you bounce back from a public professional failure?",
    "Should remote work become the default where possible?",
    "What makes a mentor truly valuable?",
    "Is changing careers mid-life brave or reckless?",
    "How much of your identity should come from your job?",
    "What's the best career advice you've ever received?",
  ],
  creative: [
    "If you wrote a book, what would it be about?",
    "Describe your perfect day as if it were a film scene.",
    "What color would you invent, and what would you call it?",
    "If your life had a soundtrack, what song plays during the opening credits?",
    "Design a brand-new holiday — what does it celebrate?",
    "What object in your home tells the best story?",
    "Invent a new word and explain what it means.",
    "What would the museum of your life exhibit?",
    "If you could redesign one city, what would you change?",
    "What's a story you've always wanted to tell but never have?",
    "Create a superpower no one has thought of before.",
    "What would your autobiography's first sentence be?",
    "If you could direct any movie, what genre would it be?",
    "Design a house with no limits — what does it have?",
    "What would the theme park of your dreams be like?",
    "Invent a new dessert — what's in it and what's it called?",
    "If you could paint one scene forever, what would it be?",
    "What fictional creature would you most want as a pet?",
    "Design a board game — what's the goal and how do you win?",
    "If your personality were a building, what would it look like?",
    "What song would you write if you could write only one?",
    "Create a brand-new sport and explain its rules.",
    "If you could design a flag for humanity, what would be on it?",
    "What would a perfume inspired by your life smell like?",
    "Invent a new genre of music — what does it sound like?",
    "If you could cast any actors in a biopic of your life, who plays you?",
    "What would the menu of your dream restaurant look like?",
    "Design a video game world — what's the central conflict?",
    "If you had to name a star, what would you call it and why?",
    "What would the cover art of your life's story look like?",
  ],
  ethics: [
    "Is it ever acceptable to lie to protect someone's feelings?",
    "Should wealthy nations open their borders completely?",
    "Is it moral to eat animals if lab-grown meat is available?",
    "Should parents have the right to choose their child's genes?",
    "Is censorship ever justified to protect society?",
    "Should voting be mandatory in democratic countries?",
    "Is it ethical to use AI to create art and sell it?",
    "Should there be a maximum wealth limit?",
    "Is pacifism always the morally correct stance?",
    "Should people be required to pass a test before having children?",
    "Is it wrong to pirate media you can't afford?",
    "Should billionaires exist?",
    "Is it ethical to keep pets?",
    "Should the wealthy pay significantly higher taxes?",
    "Is it ever right to break a law you believe is unjust?",
    "Should euthanasia be a legal right for terminally ill patients?",
    "Is it moral to have biological children in an overpopulated world?",
    "Should corporations be allowed to donate to political campaigns?",
    "Is it wrong to consume content from artists who've done terrible things?",
    "Should genetic enhancement be available to everyone or no one?",
    "Is it ethical to colonize other planets if we've ruined Earth?",
    "Should there be limits on free speech online?",
    "Is it ever acceptable to spy on your own children?",
    "Should wealth inheritance be capped?",
    "Is animal testing for medicine ever justified?",
    "Should we prioritize saving endangered species over human needs?",
    "Is it ethical to lie on a resume to get a job you can do?",
    "Should the government regulate what people eat?",
    "Is war ever the moral choice?",
    "Should apologies be legally required from corporations that harm people?",
  ],
  culture: [
    "What's a tradition from another culture you wish your country adopted?",
    "If you could live anywhere in the world for a year, where would it be?",
    "What food best represents your hometown?",
    "How does travel change a person?",
    "What's a stereotype about your culture that's completely wrong?",
    "Which language sounds the most beautiful to you?",
    "What's the most underrated travel destination?",
    "How important is preserving local traditions in a globalized world?",
    "What festival anywhere in the world would you most like to attend?",
    "Does your hometown shape who you become?",
    "What's a dish you grew up with that everyone should try?",
    "How does the place you live affect your worldview?",
    "What's a custom from your culture that outsiders often misunderstand?",
    "If you could time-travel to any era, when would you go?",
    "What's a food from another culture you wish was everywhere?",
    "How does the language you speak shape how you think?",
    "What's the most surprising thing you've learned from another culture?",
    "Should countries preserve historic buildings or make way for the new?",
    "What does 'home' mean — a place, a person, or a feeling?",
    "Which country's work culture would you most like to adopt?",
    "What's a gesture that means something totally different elsewhere?",
    "How does growing up in a city vs. the countryside change you?",
    "What's a beautiful word in another language with no direct translation?",
    "Which culture's approach to family do you admire most?",
    "What's a holiday from another country you'd love to celebrate?",
    "How does music connect people across cultures?",
    "What's a place that felt completely different from what you expected?",
    "Should traditional dress be worn more often in daily life?",
    "What's a habit from another culture that would improve your life?",
    "How do you respectfully engage with a culture that isn't yours?",
  ],
  event: [
    "Is it possible to completely avoid following the crowd, or are we all influenced by it?",
    "Why is it so much easier to join an angry crowd than to stand against one?",
    "Have you ever supported a cause just because your friends did, only to regret it later?",
    "How do you tell the difference between people speaking up for a good reason and people just attacking someone unfairly?",
    "Is 'cancel culture' just a modern way for angry crowds to attack people, or is it a good way to make people take responsibility?",
    "When everyone around you agrees on a topic, do you feel pressured to agree too?",
    "Should we always wait for all the facts before getting angry on social media?",
    "How does being hidden on the internet make people more likely to attack others as a group?",
    "Can someone be a 'detective' without becoming negative and untrusting of everyone?",
    "Is it our duty to question what most people think, even if it feels uncomfortable?",
    "Why do fake news and shocking stories spread faster than the boring truth?",
    "What's the best way to check if a shocking story is true before you share it online?",
    "Have you ever found yourself repeating an opinion you hadn't actually checked?",
    "Does the fear of being left out stop us from saying what we really think?",
    "How does social media push us to act like everyone else?",
    "Is it really possible to think for yourself when the internet is always telling you what to think?",
    "What happens when people care more about agreeing with their friends than caring about the actual truth?",
    "Should there be punishments for joining an internet group that ruins an innocent person's life?",
    "How do you handle it when a close friend shares fake news?",
    "Why do people refuse to change their minds even when you show them proof they are wrong?",
    "Is it cowardly to stay silent during a drama until you know all the facts?",
    "How can we teach the next generation to think for themselves rather than just follow the crowd?",
    "Does being very proud of your group make you judge people outside of it?",
    "When is going against the crowd brave, and when is it just being annoying for no reason?",
    "How do politicians and the media use the crowd's behavior to their advantage?",
    "Have you ever changed your mind about a big issue after doing your own research?",
    "Is 'common sense' sometimes just what everyone agrees to believe?",
    "Why do feelings spread anger faster than facts and logic?",
    "How do you know when you are only hearing people who agree with you, and how do you fix it?",
    "If the crowd is always right, why do we look back at history and realize we were wrong so often?",
  ],
};

// Flatten into Topic objects with stable ids.
export const PREBUILT_TOPICS: Topic[] = (
  Object.keys(RAW_TOPICS) as CategoryId[]
).flatMap((category) =>
  RAW_TOPICS[category].map((text, i) => {
    // Generate a stable pseudo-random spiciness level (between 1 and 3) for ALL topics
    const hash = i + text.length;
    const spiciness = (hash % 3) + 1;
    
    return {
      id: `prebuilt-${category}-${i}`,
      text,
      category,
      source: "prebuilt" as const,
      spiciness,
    };
  }),
);

export const PREBUILT_COUNT = PREBUILT_TOPICS.length;
